/**
 * petstore-server - petstore-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (Schema options: { title: \'NewProduct\', exclude: [ \'id\' ] })
 */
export interface NewProduct { 
  [key: string]: object | any;


    name: string;
    price: number;
    description: string;
}

